name: Atom CI
on: [push, pull_request]
jobs:
  atom:
    name: Atom
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.4']
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Validate Composer .json and .lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Psalm Static Analysis
        run: vendor/bin/psalm -c $GITHUB_WORKSPACE/psalm.xml --diff --diff-format=udiff --dry-run
        if: always()

      - name: PHPStan
        run: vendor/bin/phpstan analyze -c $GITHUB_WORKSPACE/phpstan.neon
        if: always()

      - name: PHPUnit
        run: vendor/bin/phpunit -c $GITHUB_WORKSPACE/phpunit.xml.dist --coverage-text
        if: always()
